export const FETCH_ALL_QUESTIONS_STARTED = 'FETCH_ALL_QUESTION_STARTED';
export const FETCH_ALL_QUESTIONS_SUCCESS = 'FETCH_ALL_QUESTIONS_SUCCESS';
export const FETCH_ALL_QUESTIONS_FAILURE = 'FETCH_ALL_QUESTIONS_FAILURE';

export const FIND_MAX_VALUE_OF_TESTS_STARTED = 'FIND_MAX_VALUE_OF_TESTS_STARTED';
export const FIND_MAX_VALUE_OF_TESTS_SUCCESS = 'FIND_MAX_VALUE_OF_TESTS_SUCCESS';
export const FIND_MAX_VALUE_OF_TESTS_FAILURE = 'FIND_MAX_VALUE_OF_TESTS_FAILURE';

export const FETCH_TEST_BY_TESTID_STARTED = 'FETCH_TEST_BY_TESTID_STARTED';
export const FETCH_TEST_BY_TESTID_SUCCESS = 'FETCH_TEST_BY_TESTID_SUCCESS';
export const FETCH_TEST_BY_TESTID_FAILURE = 'FETCH_TEST_BY_TESTID_FAILURE';